apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-webhook
data:
  sidecarconfig.yaml: |
    containers:
    - image: vault:latest
      name: vault-agent
      args:
      - agent
      - -log-level=debug
      - -config=/vault/config/agent.config
      env:
      - name: SKIP_SETCAP
        value: 'true'
      - name: VAULT_ADDR
        value: https://vault.hashicorp.svc:8200
      - name: VAULT_CAPATH
        value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      volumeMounts:
      - mountPath: /vault/config/agent.config
        subPath: agent.config
        name: vault-config
      - mountPath: /var/run/secrets/vaultproject.io
        name: vault-agent-volume
    - image: vault-agent-token-handler:latest
      name: vault-agent-token-handler
      args:
        - handler
      env:
        - name: LOG_LEVEL
          value: 'DEBUG'
        - name: VAULT_ADDR
          value: https://vault.hashicorp.svc:8200
        - name: VAULT_CAPATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        - name: VAULT_TOKEN
          value: /var/run/secrets/vaultproject.io/token
        - name: VAULT_SECRET
          value: secret/example
        - name: PROPERTIES_FILE
          value: /var/run/secrets/vaultproject.io/application.yaml
      imagePullPolicy: Always
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/vaultproject.io
        name: vault-agent-volume
    volumes:
    - name: vault-agent-volume
      emptyDir:
        medium: Memory
    - configMap:
        items:
          - key: vault-agent-config
            path: agent.config
        name: vault-agent-config
      name: vault-config