apiVersion: v1
kind: Template
objects:

- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    name: vault-agent-webhook
    labels:
      app: vault-agent-webhook
  webhooks:
    - name: vault-agent.vaultproject.io
      clientConfig:
        service:
          name: vault-agent-webhook
          namespace: hashicorp-vault
          path: "/mutate"
        caBundle: ${CA_BUNDLE}
      rules:
        - operations: [ "CREATE" ]
          apiGroups: [""]
          apiVersions: ["v1"]
          resources: ["pods"]
      namespaceSelector:
        matchLabels:
          vault-agent-webhook: enabled
parameters:
- name: CA_BUNDLE
  description: Certificate Authority to validate the services
  required: true
