apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: go-dep

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: go-dep
  name: go-dep
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: go-dep:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/arunbsar/mutating-webhook-vault-agent
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'docker.io/golang:1.11'
      dockerfilePath: Dockerfile.dep
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: H6zbzRsVbOrybRD1bQIg
    type: GitHub
  - generic:
      secret: 348BoCSjDyXzP9oNPUE4
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vault-agent-webhook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: vault-agent-webhook
  name: vault-agent-webhook
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: vault-agent-webhook:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/arunbsar/mutating-webhook-vault-agent
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: go-dep:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: H6zbzRsVbOrybRD1bQIg
    type: GitHub
  - generic:
      secret: 348BoCSjDyXzP9oNPUE4
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange

